/*
 * Swagger Petstore (Simple)
 * A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: foo@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * UserCreateRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-13T16:31:41.035Z")
public class UserCreateRequest {
  @SerializedName("email")
  private String email = null;
  @SerializedName("name")
  private String name= null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("active")
  private Boolean active = true;

  @SerializedName("roles")
  private List<String> roles = null;

  @SerializedName("joinDefaultChannels")
  private Boolean joinDefaultChannels = true;

  @SerializedName("requirePasswordChange")
  private Boolean requirePasswordChange = false;

  @SerializedName("sendWelcomeEmail")
  private Boolean sendWelcomeEmail = false;

  @SerializedName("customFields")
  private Map<String, String> customFields = null;

  public UserCreateRequest email(String email) {
    this.email = email;
    return this;
  }

  @ApiModelProperty(value = "")
   public String getName() {
	return name;
}


public void setName(String name) {
	this.name = name;
}


/**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserCreateRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserCreateRequest username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public UserCreateRequest active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public UserCreateRequest roles(List<String> roles) {
    this.roles = roles;
    return this;
  }

  public UserCreateRequest addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<String>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(List<String> roles) {
    this.roles = roles;
  }

  public UserCreateRequest joinDefaultChannels(Boolean joinDefaultChannels) {
    this.joinDefaultChannels = joinDefaultChannels;
    return this;
  }

   /**
   * Get joinDefaultChannels
   * @return joinDefaultChannels
  **/
  @ApiModelProperty(value = "")
  public Boolean getJoinDefaultChannels() {
    return joinDefaultChannels;
  }

  public void setJoinDefaultChannels(Boolean joinDefaultChannels) {
    this.joinDefaultChannels = joinDefaultChannels;
  }

  public UserCreateRequest requirePasswordChange(Boolean requirePasswordChange) {
    this.requirePasswordChange = requirePasswordChange;
    return this;
  }

   /**
   * Get requirePasswordChange
   * @return requirePasswordChange
  **/
  @ApiModelProperty(value = "")
  public Boolean getRequirePasswordChange() {
    return requirePasswordChange;
  }

  public void setRequirePasswordChange(Boolean requirePasswordChange) {
    this.requirePasswordChange = requirePasswordChange;
  }

  public UserCreateRequest sendWelcomeEmail(Boolean sendWelcomeEmail) {
    this.sendWelcomeEmail = sendWelcomeEmail;
    return this;
  }

   /**
   * Get sendWelcomeEmail
   * @return sendWelcomeEmail
  **/
  @ApiModelProperty(value = "")
  public Boolean getSendWelcomeEmail() {
    return sendWelcomeEmail;
  }

  public void setSendWelcomeEmail(Boolean sendWelcomeEmail) {
    this.sendWelcomeEmail = sendWelcomeEmail;
  }

  public UserCreateRequest customFields(Map<String, String> customFields) {
    this.customFields = customFields;
    return this;
  }

  public UserCreateRequest putCustomFieldsItem(String key, String customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<String, String>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getCustomFields() {
    return customFields;
  }

  public void setCustomFields(Map<String, String> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserCreateRequest userCreateRequest = (UserCreateRequest) o;
    return Objects.equals(this.email, userCreateRequest.email) &&
        Objects.equals(this.password, userCreateRequest.password) &&
        Objects.equals(this.username, userCreateRequest.username) &&
        Objects.equals(this.active, userCreateRequest.active) &&
        Objects.equals(this.roles, userCreateRequest.roles) &&
        Objects.equals(this.joinDefaultChannels, userCreateRequest.joinDefaultChannels) &&
        Objects.equals(this.requirePasswordChange, userCreateRequest.requirePasswordChange) &&
        Objects.equals(this.sendWelcomeEmail, userCreateRequest.sendWelcomeEmail) &&
        Objects.equals(this.customFields, userCreateRequest.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, password, username, active, roles, joinDefaultChannels, requirePasswordChange, sendWelcomeEmail, customFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserCreateRequest {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    joinDefaultChannels: ").append(toIndentedString(joinDefaultChannels)).append("\n");
    sb.append("    requirePasswordChange: ").append(toIndentedString(requirePasswordChange)).append("\n");
    sb.append("    sendWelcomeEmail: ").append(toIndentedString(sendWelcomeEmail)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

